### PR TITLE
Add Zulu locale

### PR DESCRIPTION
**Pull request by cyriaka90**
## Pull Request Checklist

Thank you for taking the time to improve Arrow! Before submitting your pull request, please check all *appropriate* boxes:

- [x] 🧪  Added **tests** for changed code.
- [x] 🛠️  All tests **pass** when run locally (run `tox` or `make test` to find out!).
- [x] 🧹  All linting checks **pass** when run locally (run `tox -e lint` or `make lint` to find out!).
- [ ] 📚  Updated **documentation** for changed code.
- [x] ⏩  Code is **up-to-date** with the `master` branch.

## Description of Changes

Adds Zulu locale. :)

### CODE REVIEW

**Review by anishnya — CHANGES_REQUESTED** [review]
This locale actually wouldn't support dehumanize at the moment. Within tests/test_arrow.py we have a separate list of locales to test on since not all locales support the week format. If you add this locale to that test list, it would fail. At the moment, any locale that has ```Mapping[TimeFrameLiteral, Union[Mapping[str, str], str]]``` doesn't support dehumanize. 

Everything else is good to go, just for the time being this locale wouldn't support dehumanize. (I'm working on a version of dehumanize that will :) )

**Comment by cyriaka90** [comment]
Ah, alright, thanks for pointing that out! :) So should I just remove Zulu from the dehumanize_locales?

**Comment by anishnya** [comment]
@cyriaka90 Yes.

**Comment by cyriaka90** [comment]
Done :)

**Review by anishnya — APPROVED** [review]
LGTM!

**Pull request merged**
