### PR TITLE
Upgrade mypy

### PR DESCRIPTION
**Pull request by gruebel**
## Pull Request Checklist

Thank you for taking the time to improve Arrow! Before submitting your pull request, please check all *appropriate* boxes:

- [ ] 🧪  Added **tests** for changed code.
- [x] 🛠️  All tests **pass** when run locally (run `tox` or `make test` to find out!).
- [x] 🧹  All linting checks **pass** when run locally (run `tox -e lint` or `make lint` to find out!).
- [ ] 📚  Updated **documentation** for changed code.
- [x] ⏩  Code is **up-to-date** with the `master` branch.

If you have *any* questions about your code changes or any of the points above, please submit your questions along with the pull request and we will try our best to help!

## Description of Changes

- Upgrade `mypy` to the newest version, because it has some nice improvements
- The newest `mypy` found a typing issue with `_ordinal_number` for `BengaliLocale`, which is correct, because it would return `None` if a negative number is passed in. This behaviour doesn't fit other locales, like `OdiaLocale` and `TamilLocale` one. I hope I made the right call here to change the return value to an empty string
- Also added error codes to the `type: ignore` comments to not automatically ignore other typing issue in the same line
- Also adjusted the `mypy` config to show the error code, when there is a typing issue and do it pretty 😄 that's how it would look like
```shell
arrow/arrow.py:173: error: "tzinfo" has no attribute "zone"  [attr-defined]
                tzinfo = parser.TzinfoParser.parse(tzinfo.zone)
                                                   ^
```

### CODE REVIEW

**Comment by krisfremen** [comment]
Hehe, yeah, but more than just mypy here. I will take a deeper look tonight.

**Comment by gruebel** [comment]
@krisfremen yeah sorry 😅 I started a small and then more and more small changes were added. I can also split the PR, if you feel more comfortable with it.

**Comment by krisfremen** [comment]
@gruebel yeah, i don't mind the PR as is, but just for clarity, but let's do the mypy stuff in this PR and split out the version bumps for the rest of the precommit and the GitHub actions in another PR.

Otherwise looks great! Thanks for contributing!

**Comment by gruebel** [comment]
@krisfremen thanks 🍻 

As suggested I split this PR into 2.

**Review by krisfremen — APPROVED** [review]
LGTM

**Pull request merged**
