### PR TITLE
Add Georgian locale

### PR DESCRIPTION
**Pull request by cyriaka90**
## Pull Request Checklist

Thank you for taking the time to improve Arrow! Before submitting your pull request, please check all *appropriate* boxes:

- [x] 🧪  Added **tests** for changed code.
- [x] 🛠️  All tests **pass** when run locally (run `tox` or `make test` to find out!).
- [x] 🧹  All linting checks **pass** when run locally (run `tox -e lint` or `make lint` to find out!).
- [ ] 📚  Updated **documentation** for changed code.
- [x] ⏩  Code is **up-to-date** with the `master` branch.

If you have *any* questions about your code changes or any of the points above, please submit your questions along with the pull request and we will try our best to help!

## Description of Changes

Adds Georgian to arrow locales. :)

### CODE REVIEW

**Comment by cyriaka90** [comment]
I don't know why `tests / windows-latest (3.7)` fails. :/ 
`tox && tox -e lint,docs `succeeded, when I ran it locally.

**Comment by anishnya** [comment]
Hey @cyriaka90, sorry for just seeing this now. @jadchaar, @systemcatch , @krisfremen any reason why we might be failing only specifically on the Windows runner? I vaguely remember us having a runner issue like this on an earlier PR a while back?

**Review by anishnya — APPROVED** [review]
LGTM!

**Comment by cyriaka90** [comment]
Thanks! Glad that it was resolved!

**Pull request merged**
