### PR TITLE
Rename requirements.txt to requirements_dev.txt

### LINKED ISSUE #926: Break down requirements.txt into separate files
We should probably break down our requirements.txt file into multiple files (e.g. one for tests, one for docs, one for standalone operation).

This will help prevent confusion and issues like https://github.com/arrow-py/arrow/issues/874.

### PR DESCRIPTION
**Pull request by systemcatch**
## Pull Request Checklist

Thank you for taking the time to improve Arrow! Before submitting your pull request, please check all *appropriate* boxes:

- [ ] 🧪  Added **tests** for changed code.
- [ ] 🛠️  All tests **pass** when run locally (run `tox` or `make test` to find out!).
- [ ] 🧹  All linting checks **pass** when run locally (run `tox -e lint` or `make lint` to find out!).
- [ ] 📚  Updated **documentation** for changed code.
- [ ] ⏩  Code is **up-to-date** with the `master` branch.

If you have *any* questions about your code changes or any of the points above, please submit your questions along with the pull request and we will try our best to help!

## Description of Changes

Idea for avoiding confusion with our install requirements, happy to take suggestions for other ways to do this though.

fixes #926

### CODE REVIEW

**Comment by jadchaar** [comment]
We may want to create a requirements folder and have a few requirements.txt files inside of them: `requirements-dev.txt` and `requirements-docs.txt`.

**Comment by systemcatch** [comment]
> We may want to create a requirements folder and have a few requirements.txt files inside of them: `requirements-dev.txt` and `requirements-docs.txt`.

We could do that but is it worth it for only 10 packages? Happy to change to that though if you prefer.

**Comment by jadchaar** [comment]
> > We may want to create a requirements folder and have a few requirements.txt files inside of them: `requirements-dev.txt` and `requirements-docs.txt`.
> 
> We could do that but is it worth it for only 10 packages? Happy to change to that though if you prefer.

I think it is worthwhile for organizational purposes. We'd need to also adjust the `tox.ini` and `Makefile` since that is where we call `pip install -r requirements.txt`.

**Comment by jadchaar** [comment]
Updated and replaced with https://github.com/arrow-py/arrow/pull/978.

**Pull request closed without merging**
