### PR TITLE
Require types-python-dateutil

### PR DESCRIPTION
**Pull request by tbekolay**
## Pull Request Checklist

- [ ] 🧪  Added **tests** for changed code.
- [x] 🛠️  All tests **pass** when run locally (run `tox` or `make test` to find out!).
- [ ] 🧹  All linting checks **pass** when run locally (run `tox -e lint` or `make lint` to find out!).
- [x] 📚  Updated **documentation** for changed code.
- [x] ⏩  Code is **up-to-date** with the `master` branch.

`tox` passes, but when I run `tox -e lint` I get a number of `ANN401 Dynamically typed expressions` errors.

I'm happy to add a test for the change but it's sort of unclear how to do this since it isn't a runtime change, it's a change that should only be picked up when running `mypy`. A short snippet that will raise an error without installing `types-python-dateutil` is:

```
(arrow.now() - arrow.now()).total_seconds()

```

## Description of Changes

Not having `types-python-dateutil` installed results in confusing errors when running `mypy` on the subtraction of two `Arrow` instances. See https://github.com/python/mypy/issues/11613 for a description of the issue, as well as some debugging from a few people.

### CODE REVIEW

**Review by krisfremen — COMMENTED** [review]
@anishnya @jadchaar @systemcatch 

would setup.py be the best place to put this?
or maybe the requirements files would be a better place?

**Comment by tbekolay** [comment]
> or maybe the requirements files would be a better place?

The requirements file does not get used when installing `arrow` through normal means like `pip install arrow`, so putting it there would not fix the issue I reference in the PR description.

**Comment by jadchaar** [comment]
Hi all thanks for the contribution here. Given that this PR now has conflicts, I have made the change in https://github.com/arrow-py/arrow/commit/3a6cd95389dfe1c93684aa083a6e3db408269fdb. Thanks a ton for raising this @tbekolay

**Comment by tbekolay** [comment]
Awesome thanks @jadchaar!

**Pull request closed without merging**
