### PR TITLE
Bump version to 1.0.1 and update CHANGELOG

### PR DESCRIPTION
**Pull request by jadchaar**
## Pull Request Checklist

Thank you for taking the time to improve Arrow! Before submitting your pull request, please check all *appropriate* boxes:

- [x] 🧪  Added **tests** for changed code.
- [x] 🛠️  All tests **pass** when run locally (run `tox` or `make test` to find out!).
- [x] 🧹  All linting checks **pass** when run locally (run `tox -e lint` or `make lint` to find out!).
- [ ] 📚  Updated **documentation** for changed code.
- [x] ⏩  Code is **up-to-date** with the `master` branch.

If you have *any* questions about your code changes or any of the points above, please submit your questions along with the pull request and we will try our best to help!

## Description of Changes

Prepares version 1.0.1 for release with a `py.typed` file bundled with Arrow (https://github.com/arrow-py/arrow/pull/925).

### CODE REVIEW

**Comment by nkitsaini** [comment]
Sorry late but I had a suggestion that we should add type-hinting to feature list of arrow. I guess for many people it's a great deal if library is type-hinted. Of course just a suggestion.

**Review by krisfremen — APPROVED** [review]
👍

**Comment by jadchaar** [comment]
> Sorry late but I had a suggestion that we should add type-hinting to feature list of arrow. I guess for many people it's a great deal if library is type-hinted. Of course just a suggestion.

Great idea @nkitsaini! Thanks for the suggestion, I will add it to the docs :).

**Review by systemcatch — APPROVED** [review]
Ship it! :boat:

**Pull request merged**
