### PR TITLE
Doc improvements

### PR DESCRIPTION
**Pull request by krisfremen**
## Pull Request Checklist

Thank you for taking the time to improve Arrow! Before submitting your pull request, please check all *appropriate* boxes:

- [ ] 🧪 Added **tests** for changed code.
- [ ] 🛠️ All tests **pass** when run locally (run `tox` or `make test` to find out!).
- [ ] 🧹 All linting checks **pass** when run locally (run `tox -e lint` or `make lint` to find out!).
- [ ] 📚 Updated **documentation** for changed code.
- [ ] ⏩ Code is **up-to-date** with the `master` branch.

If you have *any* questions about your code changes or any of the points above, please submit your questions along with the pull request and we will try our best to help!

## Description of Changes

WIP for doc improvements and audits.

### CODE REVIEW

**Comment by systemcatch** [comment]
Hey @krisfremen not sure what the status of this PR is? If it's just a case of adding pydocstyle to pre-commit then manually fixing/improving every docstring I'm happy to do that.

**Comment by krisfremen** [comment]
> Hey @krisfremen not sure what the status of this PR is? If it's just a case of adding pydocstyle to pre-commit then manually fixing/improving every docstring I'm happy to do that.

I did add pydocstyle, and I started going over the errors to fix them, have gotten busy with work, so I didn't get to finish it yet.
I didn't want to merge it in with just the pydocstyle alone for it just to fail all the time.

**Comment by krisfremen** [comment]
I see some changes were introduced, I'll rebase and do a big chunk of the docstyle errors, probably tomorrow.

**Comment by jadchaar** [comment]
Hey @krisfremen when you are free and want to take this on again, feel free to open a new PR :).

**Pull request closed without merging**
