### PR TITLE
Making the documentation more readable

### LINKED ISSUE #1134: Improving the documentation layout
The current documentation is a little difficult to navigate for a couple of reasons:

- The table of content is overflowing on the text (as highlighted in #1128)
- The doc is a long one pager...
- The search box is right at the bottom

Most of these problems would be solved by simply using a more updated sphinx theme (https://sphinx-rtd-theme.readthedocs.io/en/stable/index.html)

I've opened a PR for this. See #1135

### PR DESCRIPTION
**Pull request by haffi96**
## Pull Request Checklist

~- [ ] 🧪  Added **tests** for changed code.~ N/A
~- [ ] 🛠️  All tests **pass** when run locally (run `tox` or `make test` to find out!).~ N/A
~- [ ] 🧹  All linting checks **pass** when run locally (run `tox -e lint` or `make lint` to find out!).~ N/A
~- [ ] 📚  Updated **documentation** for changed code.~ N/A
- [x] ⏩  Code is **up-to-date** with the `master` branch.

## Description of Changes
- Changing documentation theme to `sphinx_rtd_theme` ([this](https://sphinx-rtd-theme.readthedocs.io/en/stable/))
- Makes it easier to navigate the docs
- No more overflowing toc over the documentation

Demo --> https://demo-arrow-docs.netlify.app/

Closes #1134 and #1128

### CODE REVIEW

**Comment by haffi96** [comment]
All CI checks passed except `lint`. I've updated the branch but the checks need to run again

**Comment by krisfremen** [comment]
hey @haffi96,

I re-ran the jobs that failed the first time around, but lint still seems to be failing.

**Comment by haffi96** [comment]
Thanks @krisfremen Will take a look today

**Comment by haffi96** [comment]
Hi, @krisfremen I've updated this again. `tox -e docs` was successful locally (which was the reason for CI failure). Hopefully the CI passes now 🤞🏽

**Comment by haffi96** [comment]
hm CI for windows-latest (3.9) failed 🤔 Specifically for one unit test `test_multiple_granularity`. Seems unrelated to this PR 😕

**Comment by krisfremen** [comment]
I'll re-run that one. GitHub actions seem to be having hiccups lately, a retry or two and then it magically works. 🙂

**Review by krisfremen — APPROVED** [review]

**Review by anishnya — APPROVED** [review]
LGTM!

**Pull request merged**
