### PR TITLE
Fixing plural of years and days in Hebrew

### PR DESCRIPTION
**Pull request by guyernest**
## Pull Request Checklist

Thank you for taking the time to improve Arrow! Before submitting your pull request, please check all *appropriate* boxes:

- [ ] 🧪  Added **tests** for changed code.
- [ ] 🛠️  All tests **pass** when run locally (run `tox` or `make test` to find out!).
- [ ] 🧹  All linting checks **pass** when run locally (run `tox -e lint` or `make lint` to find out!).
- [ ] 📚  Updated **documentation** for changed code.
- [ ] ⏩  Code is **up-to-date** with the `master` branch.

If you have *any* questions about your code changes or any of the points above, please submit your questions along with the pull request and we will try our best to help!

### CODE REVIEW

**Review by krisfremen — CHANGES_REQUESTED** [review]
Hi @guyernest,

Thanks for the PR.

Let's start with getting the tests to pass first, which needs to have the locale's _format_timeframe to be modified in order to use the new keys.

Take a look at the Arabic locale to see the _format_timeframe implementation, this will probably need to have the "general" keys moved to the new keys.

**Comment by guyernest** [comment]
Thank you for your attention and I apologize for missing these tests failures. 
I've fixed the format, added a couple of tests, and verified they are passing now.

**Review by krisfremen — CHANGES_REQUESTED** [review]
Hi @guyernest,

looks great in terms of code and passing tests!

The only thing left is the code style, if you take a look at the GitHub Actions, there's a few cosmetic fixups needed, you can do all of them automatically by running `tox -e lint.

Other than that, everything else looks good to go!

**Comment by guyernest** [comment]
I didn't notice any change in the files, however, it might be some whitespace characters or new lines that I don't see.

I hope now it will pass the workflow smoothly

**Review by krisfremen — APPROVED** [review]
@guyernest Thanks for fixing up your PR! That looks great! 

Looks good to me!

**Review by anishnya — APPROVED** [review]
Looks good to me as well.

**Pull request merged**
