### PR TITLE
Modifying Spelling `제작년`, Remove poorly used expressions

### PR DESCRIPTION
**Pull request by yangs1202**
## Pull Request Checklist

Thank you for taking the time to improve Arrow! Before submitting your pull request, please check all *appropriate* boxes:

- [x] 🧪  Added **tests** for changed code.
- [x] 🛠️  All tests **pass** when run locally (run `tox` or `make test` to find out!).
- [x] 🧹  All linting checks **pass** when run locally (run `tox -e lint` or `make lint` to find out!).
- [x] 📚  Updated **documentation** for changed code.
- [x] ⏩  Code is **up-to-date** with the `master` branch.

If you have *any* questions about your code changes or any of the points above, please submit your questions along with the pull request and we will try our best to help!

## Description of Changes
- The expression '그끄제' is rarely used in Korean expressions. Instead, the expression '3일전' is more natural.
- I've corrected the spelling. '재작년', not '제작년', is the right expression.

### CODE REVIEW

**Comment by yangs1202** [comment]
@jadchaar Hello? Please check this PR.

**Review by krisfremen — APPROVED** [review]
LGTM

**Comment by yangs1202** [comment]
Hello, @pothitos
First of all, thank you for making a good open source.

I am using this library very well in Korea,
I'm curious about the next release schedule.

Recently, I think you merged something similar with the master.
I'm sorry if it's rude.

Then I'll wait for your reply. Have a good day.

**Comment by yangs1202** [comment]
Hello, @jadchaar
First of all, thank you for making a good open source.

I am using this library very well in Korea,
I'm curious about the next release schedule.

Recently, I think you merged something similar with the master.
I'm sorry if it's rude.

Then I'll wait for your reply. Have a good day.

**Review by jadchaar — APPROVED** [review]

**Pull request merged**
