### PR TITLE
Add Sami locale

### PR DESCRIPTION
**Pull request by cyriaka90**
## Pull Request Checklist

Thank you for taking the time to improve Arrow! Before submitting your pull request, please check all *appropriate* boxes:

- [x] 🧪  Added **tests** for changed code.
- [x] 🛠️  All tests **pass** when run locally (run `tox` or `make test` to find out!).
- [x] 🧹  All linting checks **pass** when run locally (run `tox -e lint` or `make lint` to find out!).
- [ ] 📚  Updated **documentation** for changed code.
- [x] ⏩  Code is **up-to-date** with the `master` branch.

## Description of Changes

Adds Sami locale. :) 

References for example: https://en.wikivoyage.org/wiki/Northern_S%C3%A1mi_phrasebook

### CODE REVIEW

**Comment by anishnya** [comment]
@cyriaka90, I think this locale should support dehumanize. Do you mind adding the locale into the dehumanize test cases and in constants.py? Other than that, LGTM. @krisfremen any additional thoughts?

**Comment by cyriaka90** [comment]
Of course, I can do that! :) I will update the PR accordingly soon.

**Comment by cyriaka90** [comment]
I added the locale into the dehumanize test cases and in constants.py.

For the tests to succeed I added a blank space for future - I couldn't find a preposition/postposition for Sami here, so I assumed none is needed here, but I'm not sure what to do here to satisfy the tests more elegantly:
https://github.com/arrow-py/arrow/blob/1d1e6c78b150981f828c601177d0424af0329850/arrow/locales.py#L4909
Any thoughts?

**Comment by anishnya** [comment]
>  couldn't find a preposition/postposition for Sam

That is the most elegant solution I can think of as well. The Basque locale had a similar issue as well when it comes to supporting dehumanize (we don't have a future proposition for Basque too). I think for now, I'll merge in this PR in and I'll create a separate issue and see what I can do on the dehumanize end of things for this. 

As always, great work @cyriaka90! Also, if you have any thoughts on what should be added to the locale implementation guide, please feel free to add them on #983.

**Review by anishnya — APPROVED** [review]

**Comment by cyriaka90** [comment]
> That is the most elegant solution I can think of as well. The Basque locale had a similar issue as well when it comes to supporting dehumanize (we don't have a future proposition for Basque too). I think for now, I'll merge in this PR in and I'll create a separate issue and see what I can do on the dehumanize end of things for this.
> 
Alright, thanks! :)

> As always, great work @cyriaka90! Also, if you have any thoughts on what should be added to the locale implementation guide, please feel free to add them on #983.

Thank you! I will do so!

**Pull request merged**
