### PR TITLE
Add Maltese locale

### PR DESCRIPTION
**Pull request by cyriaka90**
## Pull Request Checklist

Thank you for taking the time to improve Arrow! Before submitting your pull request, please check all *appropriate* boxes:

- [x] 🧪  Added **tests** for changed code.
- [x] 🛠️  All tests **pass** when run locally (run `tox` or `make test` to find out!).
- [x] 🧹  All linting checks **pass** when run locally (run `tox -e lint` or `make lint` to find out!).
- [ ] 📚  Updated **documentation** for changed code.
- [x] ⏩  Code is **up-to-date** with the `master` branch.

## Description of Changes

Adds Maltese locale. :)
Also fixes two white spaces in Malay locale.

### CODE REVIEW

**Comment by anishnya** [comment]
@systemcatch Assuming #970 gets merged in, this locale should be able to support dehumanize.

**Comment by jadchaar** [comment]
@anishnya does @cyriaka90 need to add the locale to any dehumanize fixtures?

**Comment by anishnya** [comment]
@jadchaar #970 hasn't been pulled in at this moment, so currently this locale wouldn't need to be added to the dehumanize fixtures.

**Review by jadchaar — APPROVED** [review]
LGTM

**Comment by jadchaar** [comment]
Feel free to make any changes to other PRs @anishnya now that this is merged!

**Pull request merged**
